export const FETCH_HOSPITAL_REQUEST = 'FETCH_HOSPITAL_REQUEST';
export const FETCH_HOSPITAL_SUCCESS = 'FETCH_HOSPITAL_SUCCESS';
export const FETCH_HOSPITAL_ERROR = 'FETCH_HOSPITAL_ERROR';

export const CREATE_HOSPITAL_REQUEST = 'CREATE_HOSPITAL_REQUEST';
export const CREATE_HOSPITAL_SUCCESS = 'CREATE_HOSPITAL_SUCCESS';
export const CREATE_HOSPITAL_ERROR = 'CREATE_HOSPITAL_ERROR';

export const FETCH_SINGLE_HOSPITAL_REQUEST = 'FETCH_SINGLE_HOSPITAL_REQUEST';
export const FETCH_SINGLE_HOSPITAL_SUCCESS = 'FETCH_SINGLE_HOSPITAL_SUCCESS';
export const FETCH_SINGLE_HOSPITAL_ERROR = 'FETCH_SINGLE_HOSPITAL_ERROR';
