export const FETCH_HOSPITAL_REQUEST = 'FETCH_HOSPITAL_REQUEST';
export const FETCH_HOSPITAL_SUCCESS = 'FETCH_HOSPITAL_SUCCESS';
export const FETCH_HOSPITAL_ERROR = 'FETCH_HOSPITAL_ERROR';

export const CREATE_HOSPITAL_REQUEST = 'CREATE_HOSPITAL_REQUEST';
export const CREATE_HOSPITAL_SUCCESS = 'CREATE_HOSPITAL_SUCCESS';
export const CREATE_HOSPITAL_ERROR = 'CREATE_HOSPITAL_ERROR';

export const FETCH_SINGLE_HOSPITAL_REQUEST = 'FETCH_SINGLE_HOSPITAL_REQUEST';
export const FETCH_SINGLE_HOSPITAL_SUCCESS = 'FETCH_SINGLE_HOSPITAL_SUCCESS';
export const FETCH_SINGLE_HOSPITAL_ERROR = 'FETCH_SINGLE_HOSPITAL_ERROR';

export const UPDATE_HOSPITAL_REQUEST = 'UPDATE_HOSPITAL_REQUEST';
export const UPDATE_HOSPITAL_SUCCESS = 'UPDATE_HOSPITAL_SUCCESS';
export const UPDATE_HOSPITAL_ERROR = 'UPDATE_HOSPITAL_ERROR';

// DONOR
export const FETCH_DONOR_REQUEST = 'FETCH_DONOR_REQUEST';
export const FETCH_DONOR_SUCCESS = 'FETCH_DONOR_SUCCESS';
export const FETCH_DONOR_ERROR = 'FETCH_DONOR_ERROR';

export const FETCH_SINGLE_DONOR_REQUEST = 'FETCH_SINGLE_DONOR_REQUEST';
export const FETCH_SINGLE_DONOR_SUCCESS = 'FETCH_SINGLE_DONOR_SUCCESS';
export const FETCH_SINGLE_DONOR_ERROR = 'FETCH_SINGLE_DONOR_ERROR';

export const UPDATE_DONOR_REQUEST = 'UPDATE_DONOR_REQUEST';
export const UPDATE_DONOR_SUCCESS = 'UPDATE_DONOR_SUCCESS';
export const UPDATE_DONOR_ERROR = 'UPDATE_DONOR_ERROR';

// RECIPIENT
export const FETCH_RECIPIENT_REQUEST = 'FETCH_RECIPIENT_REQUEST';
export const FETCH_RECIPIENT_SUCCESS = 'FETCH_RECIPIENT_SUCCESS';
export const FETCH_RECIPIENT_ERROR = 'FETCH_RECIPIENT_ERROR';

export const FETCH_SINGLE_RECIPIENT_REQUEST = 'FETCH_SINGLE_RECIPIENT_REQUEST';
export const FETCH_SINGLE_RECIPIENT_SUCCESS = 'FETCH_SINGLE_RECIPIENT_SUCCESS';
export const FETCH_SINGLE_RECIPIENT_ERROR = 'FETCH_SINGLE_RECIPIENT_ERROR';

export const UPDATE_RECIPIENT_REQUEST = 'UPDATE_RECIPIENT_REQUEST';
export const UPDATE_RECIPIENT_SUCCESS = 'UPDATE_RECIPIENT_SUCCESS';
export const UPDATE_RECIPIENT_ERROR = 'UPDATE_RECIPIENT_ERROR';
